/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as IncidentsIndexRouteImport } from './routes/incidents/index'
import { Route as ConnectionsIndexRouteImport } from './routes/connections/index'
import { Route as SkillsSlugRouteImport } from './routes/skills/$slug'
import { Route as IncidentsIncidentIdRouteImport } from './routes/incidents/$incidentId'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdDocumentsDocumentIdRouteImport } from './routes/projects/$projectId/documents/$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIncidentIdRoute = IncidentsIncidentIdRouteImport.update({
  id: '/incidents/$incidentId',
  path: '/incidents/$incidentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdDocumentsDocumentIdRoute =
  ProjectsProjectIdDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connections': typeof ConnectionsIndexRoute
  '/incidents': typeof IncidentsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/incidents/$incidentId': typeof IncidentsIncidentIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/documents/$documentId': typeof ProjectsProjectIdDocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/incidents/$incidentId'
    | '/skills/$slug'
    | '/connections/'
    | '/incidents/'
    | '/projects/'
    | '/skills/'
    | '/projects/$projectId/'
    | '/projects/$projectId/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/incidents/$incidentId'
    | '/skills/$slug'
    | '/connections'
    | '/incidents'
    | '/projects'
    | '/skills'
    | '/projects/$projectId'
    | '/projects/$projectId/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/incidents/$incidentId'
    | '/skills/$slug'
    | '/connections/'
    | '/incidents/'
    | '/projects/'
    | '/skills/'
    | '/projects/$projectId/'
    | '/projects/$projectId/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  IncidentsIncidentIdRoute: typeof IncidentsIncidentIdRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$incidentId': {
      id: '/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof IncidentsIncidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/documents/$documentId': {
      id: '/projects/$projectId/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/projects/$projectId/documents/$documentId'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsDocumentIdRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdDocumentsDocumentIdRoute: typeof ProjectsProjectIdDocumentsDocumentIdRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdDocumentsDocumentIdRoute:
      ProjectsProjectIdDocumentsDocumentIdRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  IncidentsIncidentIdRoute: IncidentsIncidentIdRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
